[package]
name = "ptero-cli"
version = "0.1.0"
authors = ["Paweł Górski <dev.baymax42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ptero"
path = "src/lib.rs"

[[bin]]
name = "ptero_cli"
path = "src/main.rs"

[dependencies]