[package]
authors = ["Paweł Górski <dev.baymax42@gmail.com>"]
edition = "2018"
name = "ptero-cli"
version = "0.1.0"
license-file = "LICENSE"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doc = true
name = "ptero"
path = "src/lib.rs"

[[bin]]
doc = false
name = "ptero_cli"
path = "src/bin/main.rs"

[dependencies]
rand = "0.7.3"
log = "0.4"
pretty_env_logger = "0.4.0"
clap = "3.0.0-beta.2"
spinners = "1.2.0"
regex = "1.4.2"
colored = "2"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
