name: Rust

on:
  push:
    tags: '*'
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Prepare environment
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      # Run checks and tests
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      # Collect coverage and upload to Coveralls
      - uses: actions-rs/grcov@v0.1

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
  
      # Build the binary
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all --release
  
      - name: Strip and rename
        run: |
          strip target/release/ptero_cli
          mv target/release/ptero_cli target/release/ptero_cli_amd64

      # Release if the tag was pushed
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/ptero_cli_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}